config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
	root   'static_pages#home'
	# get '/help', to: 'static_pages#help'
	get    '/signup',  to: 'users#new'
	get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :accomplishments
	resources :users
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :accomplishments
end

app/models/accomplishment.rb
class Accomplishment < ApplicationRecord
	belongs_to :user
	default_scope -> { order(date: :desc) }
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 60 }
	validates :timeWorking, presence: true, numericality: { greater_than_or_equal_to: 5 }
	validates :timeProductive, presence: true, numericality: { greater_than_or_equal_to: 0 }
	validate :time_productive_leq_working

	def time_productive_leq_working
	  errors[:base] << "Time productive must be less than or equal to the amount of time productive (both in minutes)." unless timeWorking > timeProductive
	end
end

app/controllers/accomplishments_controller.rb
class AccomplishmentsController < ApplicationController
	before_action :logged_in_user, 	only: [:index, :create, :edit, :update, :destroy]
	before_action :correct_user,		only: [:destroy, :show, :edit, :update]

	def index
	  @accomplishments = current_user.accomplishments.all

	  respond_to do |format|
	    format.html
	    format.json { render json: @accomplishments }
	  end
	end

	def new
	end

	def create
		@accomplishment = current_user.accomplishments.build(accomplishment_params)
		if @accomplishment.save
			flash[:success] = "Accomplishment created!"
			redirect_to root_url
		else
			render 'static_pages/home'
		end
	end

  def destroy
		@accomplishment.destroy
		flash[:success] = "Accomplishment deleted"
		redirect_to request.referrer || root_url
  end

	def edit
	end

	def update
		if @accomplishment.update(accomplishment_params)
			redirect_to @accomplishment
			flash[:sucess] = "Accomplishment was successfully updated."
		else
			render :edit
			flash[:danger] = "Unsuccessful update for the accomplishment."
		end
	end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def accomplishment_params
      params.require(:accomplishment).permit(:name, :timeWorking, :timeProductive, :date)
    end

		def correct_user
			@accomplishment = current_user.accomplishments.find_by(id: params[:id])
			redirect_to root_url if @accomplishment.nil?
		end
end

app/helpers/accomplishments_helper.rb
module AccomplishmentsHelper
end

app/views/accomplishments/_accomplishment.html.erb
<li id="accomplishment-<%= accomplishment.id %>">
  <span class="name"><%= accomplishment.name %></span>
	<span class="timeWorking"><%= accomplishment.timeWorking %> minutes </span>
	<span class="timeProductive"><%= ((accomplishment.timeProductive / accomplishment.timeWorking ) * 100).round(2)  %>% productive</span>
  <span class="timestamp">
    Accomplished <%= time_ago_in_words(accomplishment.date) %> ago.
		<% if current_user?(accomplishment.user) %>
			<%= link_to "delete", accomplishment, method: :delete,
																					 data: { confirm: "Are you sure?" } %>
		<% end %>
	</span>
</li>

app/views/accomplishments/_form.html.erb
<%= form_with(model: accomplishment, local: true) do |form| %>
  <% if accomplishment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accomplishment.errors.count, "error") %> prohibited this accomplishment from being saved:</h2>

      <ul>
      <% accomplishment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "Time Working (minutes)" %>
    <%= form.text_field :timeWorking %>
  </div>

  <div class="field">
    <%= form.label "Time Productive (minutes)" %>
    <%= form.text_field :timeProductive %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accomplishments/edit.html.erb
<h1>Editing Accomplishment</h1>

<%= render 'form', accomplishment: @accomplishment %>

<%= link_to 'Show', @accomplishment %> |
<%= link_to 'Back', accomplishments_path %>

app/views/accomplishments/index.html.erb
<script type="text/javascript">
	loadData();
</script>
<h1 class="plotTitle">Productivity vs Time Working on Task</h1>
<div id="plot-container">
	<svg id="prodWorking"></svg>
</div>
<br/>
<br/>
<br/>
<h1 class="plotTitle">Productivity Over Time</h1>
<div id="plot-container">
	<svg id="timeProd"></svg>
</div>

app/views/accomplishments/new.html.erb
<h1>New Accomplishment</h1>

<%= render 'form', accomplishment: @accomplishment %>

<%= link_to 'Back', accomplishments_path %>

app/views/accomplishments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @accomplishment.name %>
</p>

<p>
  <strong>Time working:</strong>
  <%= @accomplishment.timeWorking %>
</p>

<p>
  <strong>Time productive:</strong>
  <%= @accomplishment.timeProductive %>
</p>

<p>
  <strong>Date:</strong>
  <%= @accomplishment.date %>
</p>

<%= link_to 'Edit', edit_accomplishment_path(@accomplishment) %> |
<%= link_to 'Back', current_user %>